language: node_js

node_js:
  - "stable"

dist: trusty
sudo: false

cache:
  directories:
    - ~/.npm
    - ~/.cache

env:
  - CI=true

before_script:
  - npm i -g gatsby
  - npm ci

script:
  - npm run lint
  - npm run test:e2e:ci
  - npm run build

deploy:
  provider: script
  script: "curl -X POST -d '' https://api.netlify.com/build_hooks/5ba3c8da1f12b70cbbcaa1a3"
  skip_cleanup: true
  on:
    branch: master