# explicit commands for building the site
# and the folder to publish
[build]
command = "gatsby build"
publish = "public"
  [build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
    resultMode = "warn"

# Commented out until https://github.com/cypress-io/netlify-plugin-cypress/issues/58 is fixed
#[[plugins]]
#  # local Cypress plugin will test our site after it is built
#  package = "netlify-plugin-cypress"
#    [plugins.inputs]
#      record = true
