# explicit commands for building the site
# and the folder to publish
[build]
command = "gatsby build"
publish = "public"
  [build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[[plugins]]
  # local Cypress plugin will test our site after it is built
  package = "netlify-plugin-cypress"
    [plugins.inputs]
      record = true

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
    # optional, fails build when a category is below a threshold
    [plugins.inputs.thresholds]
    seo = 0.9
    pwa = 0.9

[[plugins]]
  package = "netlify-plugin-checklinks"

[[plugins]]
  package = "netlify-plugin-a11y"
  [plugins.inputs]
    resultMode = "warn"
