name: Deploy to Netlify

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: npm Cache Folder
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    # In order to make gatsby incremental build works, it's necessary .cache
    # and public folder.
    - name: Gatsby Cache Folder
      uses: actions/cache@v2
      id: gatsby-cache-folder
      with:
        path: .cache
        key: ${{ runner.os }}-cache-gatsby
        restore-keys: |
          ${{ runner.os }}-cache-gatsby

    - name: Gatsby Public Folder
      uses: actions/cache@v2
      id: gatsby-public-folder
      with:
        path: public/
        key: ${{ runner.os }}-public-gatsby
        restore-keys: |
          ${{ runner.os }}-public-gatsby
      
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.15.0
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
    
    - name: Run E2E tests
      uses: cypress-io/github-action@v2
      env:
        # incremental builds
        # https://www.gatsbyjs.org/docs/page-build-optimizations-for-incremental-data-changes/
        GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
        NODE_ENV: production
      with:
        # we have already installed all dependencies above
        install: false
        start: npm run test:e2e:ci
        # quote the url to be safe against YML parsing surprises
        wait-on: 'http://localhost:8000'
        wait-on-timeout: 600
      
    - name: Deploy to Netlify
      if: job.status == 'success'
      run: curl -X POST -d '' https://api.netlify.com/build_hooks/5ba3c8da1f12b70cbbcaa1a3 && curl -X POST -d {} https://api.netlify.com/build_hooks/5daf5f3d31ede3a743f5bebc
