name: Deploy to Netlify

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: npm Cache Folder
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
      
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 14.15.0
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Deploy to Netlify
      if: job.status == 'success'
      run: curl -X POST -d '' https://api.netlify.com/build_hooks/5ba3c8da1f12b70cbbcaa1a3 && curl -X POST -d {} https://api.netlify.com/build_hooks/5daf5f3d31ede3a743f5bebc
