name: Deploy to Netlify

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-16.04
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v1
      
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.13.1
        
    - name: Install Gatsby
      run: npm i -g gatsby
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
    
    - name: Run tests
      uses: cypress-io/github-action@v1
      timeout-minutes: 10
      with:
        # we have already installed all dependencies above
        install: false
        # serve locally
        start: npm start
        # quote the url to be safe against YML parsing surprises
        wait-on: 'http://localhost:8000'
        wait-on-timeout: 600
    
    - name: Build app
      run: npm run build
      
    - name: Deploy to Netlify
      if: job.status == 'success'
      run: curl -X POST -d '' https://api.netlify.com/build_hooks/5ba3c8da1f12b70cbbcaa1a3 && curl -X POST -d {} https://api.netlify.com/build_hooks/5daf5f3d31ede3a743f5bebc
